/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author vergo
 */
public class JDlgFsvFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgFsvFornecedor
     */
    public JDlgFsvFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Fornecedor");
        setLocationRelativeTo(null);
        desabilitar();
    }
    
    public void habilitar(){
        jBtnFsvConfirmar.setEnabled(true);
        jBtnFsvCancelar.setEnabled(true);
        jTxtFsvCodigo.setEnabled(true);
        jTxtFsvNome.setEnabled(true);
        jTxtFsvRepresentante.setEnabled(true);
        jTxtFsvTipo.setEnabled(true);
        jTxtFsvEmail.setEnabled(true);
        jTxtFsvEndereco.setEnabled(true);
        jTxtFsvCidade.setEnabled(true);
        jTxtFsvBairro.setEnabled(true);
        jFmtFsvCEP.setEnabled(true);
        jFmtFsvCNPJ.setEnabled(true);
        jFmtFsvSite.setEnabled(true);
        jFmtFsvTelefone.setEnabled(true);
        jFmtFsvWhatsapp.setEnabled(true);
        jCboFsvEstado.setEnabled(true);
        jChFsvAtivo.setEnabled(true);
        jBtnFsvAlterar.setEnabled(false);
        jBtnFsvIncluir.setEnabled(false);
        jBtnFsvPesquisar.setEnabled(false);
        jBtnFsvExcluir.setEnabled(false);
    }
    
    public void desabilitar(){
        jBtnFsvConfirmar.setEnabled(false);
        jBtnFsvCancelar.setEnabled(false);
        jTxtFsvCodigo.setEnabled(false);
        jTxtFsvNome.setEnabled(false);
        jTxtFsvRepresentante.setEnabled(false);
        jTxtFsvTipo.setEnabled(false);
        jTxtFsvEmail.setEnabled(false);
        jTxtFsvEndereco.setEnabled(false);
        jTxtFsvCidade.setEnabled(false);
        jTxtFsvBairro.setEnabled(false);
        jFmtFsvCEP.setEnabled(false);
        jFmtFsvCNPJ.setEnabled(false);
        jFmtFsvSite.setEnabled(false);
        jFmtFsvTelefone.setEnabled(false);
        jFmtFsvWhatsapp.setEnabled(false);
        jCboFsvEstado.setEnabled(false);
        jChFsvAtivo.setEnabled(false);
        jBtnFsvAlterar.setEnabled(true);
        jBtnFsvIncluir.setEnabled(true);
        jBtnFsvPesquisar.setEnabled(true);
        jBtnFsvExcluir.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtFsvCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtFsvNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jFmtFsvCNPJ = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFmtFsvWhatsapp = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFmtFsvTelefone = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtFsvEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFmtFsvCEP = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jCboFsvEstado = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTxtFsvCidade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtFsvBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtFsvEndereco = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTxtFsvRepresentante = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTxtFsvTipo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jFmtFsvSite = new javax.swing.JFormattedTextField();
        jChFsvAtivo = new javax.swing.JCheckBox();
        jBtnFsvIncluir = new javax.swing.JButton();
        jBtnFsvAlterar = new javax.swing.JButton();
        jBtnFsvExcluir = new javax.swing.JButton();
        jBtnFsvConfirmar = new javax.swing.JButton();
        jBtnFsvCancelar = new javax.swing.JButton();
        jBtnFsvPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("CNPJ");

        jLabel4.setText("WhatsApp");

        jLabel5.setText("Telefone (fixo)");

        jLabel6.setText("E-mail");

        jTxtFsvEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFsvEmailActionPerformed(evt);
            }
        });

        jLabel7.setText("CEP");

        jLabel8.setText("Estado");

        jCboFsvEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Cidade");

        jLabel10.setText("Bairro");

        jLabel11.setText("Endereço");

        jTxtFsvEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFsvEnderecoActionPerformed(evt);
            }
        });

        jLabel12.setText("Representante");

        jLabel13.setText("Tipo");

        jTxtFsvTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFsvTipoActionPerformed(evt);
            }
        });

        jLabel14.setText("Site");

        jChFsvAtivo.setText("Ativo");

        jBtnFsvIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnFsvIncluir.setMnemonic('i');
        jBtnFsvIncluir.setText("Incluir");
        jBtnFsvIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFsvIncluirActionPerformed(evt);
            }
        });

        jBtnFsvAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnFsvAlterar.setMnemonic('a');
        jBtnFsvAlterar.setText("Alterar");
        jBtnFsvAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFsvAlterarActionPerformed(evt);
            }
        });

        jBtnFsvExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnFsvExcluir.setMnemonic('e');
        jBtnFsvExcluir.setText("Excluir");
        jBtnFsvExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFsvExcluirActionPerformed(evt);
            }
        });

        jBtnFsvConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnFsvConfirmar.setMnemonic('c');
        jBtnFsvConfirmar.setText("Confirmar");
        jBtnFsvConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFsvConfirmarActionPerformed(evt);
            }
        });

        jBtnFsvCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnFsvCancelar.setMnemonic('c');
        jBtnFsvCancelar.setText("Cancelar");
        jBtnFsvCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFsvCancelarActionPerformed(evt);
            }
        });

        jBtnFsvPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnFsvPesquisar.setMnemonic('p');
        jBtnFsvPesquisar.setText("Pesquisar");
        jBtnFsvPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFsvPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnFsvIncluir)
                        .addGap(66, 66, 66)
                        .addComponent(jBtnFsvAlterar)
                        .addGap(53, 53, 53)
                        .addComponent(jBtnFsvExcluir))
                    .addComponent(jLabel14)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jFmtFsvCNPJ, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtFsvCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(80, 80, 80)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2)
                                        .addComponent(jFmtFsvWhatsapp, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE))
                                    .addGap(36, 36, 36)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jFmtFsvTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jTxtFsvNome)))
                        .addComponent(jTxtFsvEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jFmtFsvCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtFsvRepresentante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                                    .addComponent(jTxtFsvBairro, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGap(83, 83, 83)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jCboFsvEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(243, 243, 243))
                                        .addComponent(jTxtFsvCidade)))
                                .addComponent(jTxtFsvEndereco)
                                .addComponent(jTxtFsvTipo)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBtnFsvConfirmar)
                                .addComponent(jFmtFsvSite, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jChFsvAtivo))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(jBtnFsvCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                    .addComponent(jBtnFsvPesquisar))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFsvCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFsvNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtFsvCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtFsvWhatsapp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtFsvTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtFsvEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtFsvCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboFsvEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFsvCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFsvBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFsvEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtFsvRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtFsvTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtFsvSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChFsvAtivo))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnFsvIncluir)
                    .addComponent(jBtnFsvAlterar)
                    .addComponent(jBtnFsvExcluir)
                    .addComponent(jBtnFsvConfirmar)
                    .addComponent(jBtnFsvCancelar)
                    .addComponent(jBtnFsvPesquisar))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFsvEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFsvEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFsvEmailActionPerformed

    private void jTxtFsvEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFsvEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFsvEnderecoActionPerformed

    private void jTxtFsvTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFsvTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFsvTipoActionPerformed

    private void jBtnFsvExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFsvExcluirActionPerformed
    JOptionPane.showConfirmDialog(null, "Confirmar a Exclusão?", "Selecione", JOptionPane.YES_NO_OPTION);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFsvExcluirActionPerformed

    private void jBtnFsvPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFsvPesquisarActionPerformed
    JOptionPane.showConfirmDialog(null, "Entre com o Código do Fornecedor");
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFsvPesquisarActionPerformed

    private void jBtnFsvAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFsvAlterarActionPerformed
        habilitar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFsvAlterarActionPerformed

    private void jBtnFsvIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFsvIncluirActionPerformed
        habilitar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFsvIncluirActionPerformed

    private void jBtnFsvCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFsvCancelarActionPerformed
        desabilitar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFsvCancelarActionPerformed

    private void jBtnFsvConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFsvConfirmarActionPerformed
        desabilitar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFsvConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgFsvFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgFsvFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgFsvFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgFsvFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgFsvFornecedor dialog = new JDlgFsvFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnFsvAlterar;
    private javax.swing.JButton jBtnFsvCancelar;
    private javax.swing.JButton jBtnFsvConfirmar;
    private javax.swing.JButton jBtnFsvExcluir;
    private javax.swing.JButton jBtnFsvIncluir;
    private javax.swing.JButton jBtnFsvPesquisar;
    private javax.swing.JComboBox<String> jCboFsvEstado;
    private javax.swing.JCheckBox jChFsvAtivo;
    private javax.swing.JFormattedTextField jFmtFsvCEP;
    private javax.swing.JFormattedTextField jFmtFsvCNPJ;
    private javax.swing.JFormattedTextField jFmtFsvSite;
    private javax.swing.JFormattedTextField jFmtFsvTelefone;
    private javax.swing.JFormattedTextField jFmtFsvWhatsapp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtFsvBairro;
    private javax.swing.JTextField jTxtFsvCidade;
    private javax.swing.JTextField jTxtFsvCodigo;
    private javax.swing.JTextField jTxtFsvEmail;
    private javax.swing.JTextField jTxtFsvEndereco;
    private javax.swing.JTextField jTxtFsvNome;
    private javax.swing.JTextField jTxtFsvRepresentante;
    private javax.swing.JTextField jTxtFsvTipo;
    // End of variables declaration//GEN-END:variables
}
