/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author vergo
 */
public class JfrmFsvPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JfrmFsvPrincipal
     */
    public JfrmFsvPrincipal() {
        initComponents();
        setTitle("Sistema de Cosméticos");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuFsvCadastros = new javax.swing.JMenu();
        jMnuFsvUsuarios = new javax.swing.JMenuItem();
        jMnuFsvClientes = new javax.swing.JMenuItem();
        jMnuFsvFornecedor = new javax.swing.JMenuItem();
        jMnuFsvProdutos = new javax.swing.JMenuItem();
        jMnuFsvVendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuFsvSair = new javax.swing.JMenuItem();
        jMnuFsvMovimentos = new javax.swing.JMenu();
        jMnuFsvVenda = new javax.swing.JMenuItem();
        jMnuFsvVendaProduto = new javax.swing.JMenuItem();
        jMnuFsvCompra = new javax.swing.JMenuItem();
        jMnuFsvCompraProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuFsvCadastros.setMnemonic('c');
        jMnuFsvCadastros.setText("Cadastros");
        jMnuFsvCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFsvCadastrosActionPerformed(evt);
            }
        });

        jMnuFsvUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFsvUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuFsvUsuarios.setMnemonic('u');
        jMnuFsvUsuarios.setText("Usuarios");
        jMnuFsvUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFsvUsuariosActionPerformed(evt);
            }
        });
        jMnuFsvCadastros.add(jMnuFsvUsuarios);

        jMnuFsvClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFsvClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuFsvClientes.setMnemonic('c');
        jMnuFsvClientes.setText("Clientes");
        jMnuFsvClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFsvClientesActionPerformed(evt);
            }
        });
        jMnuFsvCadastros.add(jMnuFsvClientes);

        jMnuFsvFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFsvFornecedor.setMnemonic('f');
        jMnuFsvFornecedor.setText("Fornecedor");
        jMnuFsvFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuFsvFornecedorActionPerformed(evt);
            }
        });
        jMnuFsvCadastros.add(jMnuFsvFornecedor);

        jMnuFsvProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFsvProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuFsvProdutos.setMnemonic('p');
        jMnuFsvProdutos.setText("Produtos");
        jMnuFsvCadastros.add(jMnuFsvProdutos);

        jMnuFsvVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFsvVendedor.setMnemonic('v');
        jMnuFsvVendedor.setText("Vendedor");
        jMnuFsvCadastros.add(jMnuFsvVendedor);
        jMnuFsvCadastros.add(jSeparator1);

        jMnuFsvSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFsvSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuFsvSair.setMnemonic('s');
        jMnuFsvSair.setText("Sair");
        jMnuFsvCadastros.add(jMnuFsvSair);

        jMenuBar1.add(jMnuFsvCadastros);

        jMnuFsvMovimentos.setMnemonic('m');
        jMnuFsvMovimentos.setText("Movimentos");

        jMnuFsvVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFsvVenda.setMnemonic('v');
        jMnuFsvVenda.setText("Venda");
        jMnuFsvMovimentos.add(jMnuFsvVenda);

        jMnuFsvVendaProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFsvVendaProduto.setMnemonic('v');
        jMnuFsvVendaProduto.setText("Venda_Produto");
        jMnuFsvMovimentos.add(jMnuFsvVendaProduto);

        jMnuFsvCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFsvCompra.setMnemonic('c');
        jMnuFsvCompra.setText("Compra");
        jMnuFsvMovimentos.add(jMnuFsvCompra);

        jMnuFsvCompraProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuFsvCompraProduto.setMnemonic('c');
        jMnuFsvCompraProduto.setText("Compra_Produto");
        jMnuFsvMovimentos.add(jMnuFsvCompraProduto);

        jMenuBar1.add(jMnuFsvMovimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuFsvCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFsvCadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuFsvCadastrosActionPerformed

    private void jMnuFsvUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFsvUsuariosActionPerformed
        JDlgFsvUsuarios jDlgFsvUsuarios = new JDlgFsvUsuarios(null, true);
        jDlgFsvUsuarios.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMnuFsvUsuariosActionPerformed

    private void jMnuFsvClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFsvClientesActionPerformed
        JDlgFsvClientes jDlgFsvClientes = new JDlgFsvClientes(null, true);
        jDlgFsvClientes.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuFsvClientesActionPerformed

    private void jMnuFsvFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuFsvFornecedorActionPerformed
        JDlgFsvFornecedor jDlgFsvFornecedor = new JDlgFsvFornecedor(null, true);
        jDlgFsvFornecedor.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuFsvFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmFsvPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmFsvPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmFsvPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmFsvPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfrmFsvPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuFsvCadastros;
    private javax.swing.JMenuItem jMnuFsvClientes;
    private javax.swing.JMenuItem jMnuFsvCompra;
    private javax.swing.JMenuItem jMnuFsvCompraProduto;
    private javax.swing.JMenuItem jMnuFsvFornecedor;
    private javax.swing.JMenu jMnuFsvMovimentos;
    private javax.swing.JMenuItem jMnuFsvProdutos;
    private javax.swing.JMenuItem jMnuFsvSair;
    private javax.swing.JMenuItem jMnuFsvUsuarios;
    private javax.swing.JMenuItem jMnuFsvVenda;
    private javax.swing.JMenuItem jMnuFsvVendaProduto;
    private javax.swing.JMenuItem jMnuFsvVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
